export const ContactList = [
  {
    id: 0,
    firstName: 'Veronica',
    lastName: 'Shei',
    phoneNumber: 8082660688,
    email: 'veronica@gmail.com',
  },
  {
    id: 1,
    firstName: 'Hudson',
    lastName: 'Lim',
    phoneNumber: 8087622494,
    email: 'hudson@gmail.com',
  },
  {
    id: 2,
    firstName: 'Tyler',
    lastName: 'Smith',
    phoneNumber: 4172920011,
    email: 'hudson@gmail.com',
  },
  {
    id: 3,
    firstName: 'Anna',
    lastName: 'Wendell',
    phoneNumber: 4172829821,
    email: 'anna@gmail.com',
  },
  {
    id: 4,
    firstName: 'Linda',
    lastName: 'Liu',
    phoneNumber: 9142728899,
    email: 'linda@gmail.com',
  },
  {
    id: 5,
    firstName: 'Derek',
    lastName: 'Yagi',
    phoneNumber: 8082149211,
    email: 'derek@gmail.com',
  },
  {
    id: 6,
    firstName: 'Miles',
    lastName: 'Hernandez',
    phoneNumber: 9142120011,
    email: 'miles@gmail.com',
  },
];
